---
- name: Get automation controller name
  kubernetes.core.k8s_info:
    api_version: automationcontroller.ansible.com/v1beta1
    kind: AutomationController
    namespace: "{{ ansible-namespace }}"
  register: automationcontroller_list

#Assumption svc name is controllername-service
- name: Create the monitor metrics label
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ automationcontroller_list | community.general.json_query('resources[0].metadata.name') }}-service"
        namespace: "{{ ansible-namespace }}"
        labels:
          monitor: "{{ monitor-value }}"
