- name: Installing configuration in AWS instance
  hosts: all
  collections:
    - amazon.aws
    - rlopez.fest_demo
    - ansible.utils
    - community.general
    - containers.podman

  tasks:
    - name: Install podman
      ansible.builtin.include_role:
        name: rlopez.fest_demo.aws
        tasks_from: 25_aws_config.yml

    - name: Install app
      ansible.builtin.include_role:
        name: rlopez.fest_demo.app
        tasks_from: 10_app_create.yml
    
    - name: Check app
      ansible.builtin.include_role:
        name: rlopez.fest_demo.app
        tasks_from: 20_check_app.yml

    - name: Delete aws instance
      ansible.builtin.include_role:
        name: rlopez.fest_demo.aws
        tasks_from: 30_delete_ec2.yml
